- alias: meren
  official: True
  name: A. Murat Eren (Meren)
  tenure_start: 10/2015
  role: PI
  twitter: merenbey
  github: meren
  web: http://meren.org
  avatar: bio-meren.jpg
  email: a.murat.eren@gmail.com
  twitter: merenbey
  github: meren
  linkedin: meren
  phone: +1-773-702-5935
  fax: +1-773-702-2281
  skype: a.murat.eren
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9118, Chicago, IL 60637 USA
  bio: "I am a computer scientist with a deep appreciation for the complexity of life. I design algorithms and experiments to better understand microbes and their ecology."
  affiliations:
    - title: MBL Fellow
      inst: Marine Biological Laboratory
      inst_link: http://www.mbl.edu/research/mbl-fellows/a-murat-eren/
    - title: Assistant Professor
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/
    - title: Committee on Microbiology
      inst: The Biomedical Sciences Cluster at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/

- alias: tom
  official: True
  name: Tom O. Delmont
  tenure_start: 10/2015
  role: Post-doctoral Scientist
  email: tom.o.delmont@gmail.com
  twitter: tomodelmont
  avatar: bio-tom.jpg
  skype: tom.o.delmont
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am a microbial ecologist who seeks to understand small and large-scale ecological patterns in the microbial world. My most recent investigations focused on humans, pristine soils, and the Southern Ocean."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: sonny
  official: True
  name: Sonny T. M. Lee
  tenure_start: 05/2016
  role: Post-doctoral Scientist
  email: leet1@uchicago.edu
  avatar: bio-sonny.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am a microbiologist studying the most interesting inhabitants of humans, coral reefs, and the ocean, and using big data to answer vexing problems of our future."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: alon
  official: True
  name: Alon Shaiber
  tenure_start: 10/2016
  role: Graduate Student
  email: alon.shaiber@gmail.com
  github: ShaiberAlon
  skype: alon.shaiber
  avatar: bio-alon.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I'm a graduate student at the Bio Physical Sciences Program at UChicago. I'm fascinated by the complexity of microbial ecology and interested in applying and developing computational tools to explore it."
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/


- alias: andrea
  official: True
  name: Andrea Watson
  tenure_start: 06/2017
  role: Rotating Graduate Student
  email: andreawatson@uchicago.edu
  avatar: bio-andrea.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am interested in combining wet lab and computational methods in a complementary way to answer microbiological questions."
  affiliations:
    - title: Graduate Student
      inst: Committee on Microbiology at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/page/microbiology

- alias: alan
  official: True
  name: Alan Selewa
  tenure_start: 05/2017
  role: Rotating Graduate Student
  email: selewa@uchicago.edu
  avatar: bio-alan.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "Machine learning for metagenomics and pangenomics"
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/

- alias: evan
  official: True
  name: Evan Kiefl
  tenure_start: 04/2017
  role: Graduate Student
  twitter: ecneicScience
  github: ekiefl
  linkedin: evan-kiefl-825985b7
  email: kiefl.evan@gmail.com
  avatar: bio-evan.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am interested in uncovering how single nucleotide variants map to functional variation in the genes of naturally-occuring microbial populations."
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/

- alias: ozcan
  official: True
  name: Özcan C. Esen
  tenure_start: 02/2016
  role: Software guru, local hacker
  email: ozcanesen@gmail.com
  twitter: ozcanesen
  avatar: bio-ozcan.jpg
  github: ozcanesen
  web: http://blog.ozcanesen.com/
  bio: "As a computer engineer I strive to utilize my expertise to investigate challenges in microbial ecology, metagenomics, and visualization of complex data."
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  affiliations:
    - title: Programmer
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: steven
  name: Steven Cui
  nick_name: Steven
  tenure_start: 07/2016
  tenure_end: 10/2016
  current_info: an undergraduate student studying computer science at the <a href="https://www.cs.uchicago.edu/">Department of Computer Science at the University of Chicago</a>
  official: True
  role: Summer Student
  avatar: bio-steven.png
  email: stevencui729@gmail.com
  bio: "I am an undergraduate student at UChicago studying computer science. I look forward to tackling new and exciting computational problems in the field of bionformatics."
  affiliations:
    - title: Undergraduate Student
      inst: The Department of Computer Science at the University of Chicago
      inst_link: https://www.cs.uchicago.edu/

- alias: kota
  official: True
  name: Kota Bear
  web: https://en.wikipedia.org/wiki/Poodle
  tenure_start: 01/2017
  role: Dog
  avatar: bio-kota.png
  address: Chicago, IL
  bio: "I focus on members of the family Sciuridae and Leporidae to study stress-induced behavioral changes in mammals."
  affiliations:
    - title: Honorary Member

- alias: mike
  name: Mike Lee
  role: Contributing hero
  twitter: AstrobioMike

- alias: veronika
  name: Veronika Kivenson
  role: Contributing hero
  web: http://methane.geol.ucsb.edu/Home.html
  twitter: v_kivenson

- alias: antti
  name: Antti Karkman
  role: Contributing hero
  github: karkman
